databases:
  - name: mudaeviewerdb
    plan: free
    databaseName: mudaeviewer
    user: mudaeviewer

services:
  - type: web
    plan: free
    name: mudae-viewer-list
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python manage.py migrate && python -m gunicorn mudae_project.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mudaeviewerdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4